first commit
IGNF/geoportal-sdk pull request #68
Opened 2020-10-27 14:02 UTC by pjjmunier

## Pull request checklist

Verifiez que votre Pull Request remplit les conditions suivantes :
- [ ] Des tests ont été ajoutés pour les changements (corrections de bugs ou features)
- [ ] De la documentation a été mise à jour ou ajoutée si nécessaire (corrections de bugs ou features)
- [x] Un build (`npm run build`) a été lancé localement et s'est correctement déroulé
- [x] Les exemples impactés par les modifications (`npm run samples`) ont été testés et validés localement
- [x] Les tests (`npm run test`) sont passés localement

## Type de Pull request

 

 

Quel type de changement cette Pull Request introduit-elle :
- [ ] Bugfix
- [ ] Feature
- [ ] Mise à jour du style du code (syntaxe, renommage de fonctions)
- [ ] Refactoring (lisibilité/performance du code, sans changements fonctionnels)
- [ ] Changement sur le processus de build
- [ ] Contenu de la documentation
- [x] Autres (décrire ci-après) : maj dépendance

## Cette PR introduit-elle des breaking changes ?

- [ ] Oui
- [x] Non

2020-11-16 18:05 UTC, elias75015 reviewed
J'ai pas commencé la review, mais il faut bien tester cette branche avec la branche ol6 côté extensions ?

2020-11-16 22:08 UTC, pjjmunier commented
Non les 2 branches sont indépendantes

2020-11-16 22:08 UTC, pjjmunier commented
Oui

2021-02-15 14:08 UTC, lowzonenose reviewed
# Review (2D)

> OpenLayers 6 & le vecteur tuilé

## Dependances

versions :

* "ol": "6.4.3",
* "ol-mapbox-style": "4.2.1",
* "itowns": "2.25.0",
* "proj4": "2.6.2",
* "three": "0.117.1",
* "three.meshline": "1.2.0",

PR#280 : https://github.com/IGNF/geoportal-extensions/pull/280

* "geoportal-extensions-itowns": "version extensions PR#280",
* "geoportal-extensions-openlayers": "version extensions PR#280",

[x] **TODO :**
> la version de la dependance "ol-mapbox-style" ne me semble pas adaptée à openlayers 6.4.0 !? UPGRADE !!!

cf. https://github.com/openlayers/ol-mapbox-style/blob/master/CHANGELOG.md

## Jouer les exemples

* http://localhost/geoportal-sdk/samples/3d/page-switch-bundle.html

![Capture-1](https://user-images.githubusercontent.com/10401006/107956121-fde39b00-6f9e-11eb-8bb8-98d6b873661c.png)

## Test performance

> tests avec **devTools** de Chrome : *Memory* et *Performance*

Page exemple pour le test :

* samples/2d/page-mapbox-accesstoken-bundle.html
* samples/2d/page-mapbox-osm-bundle.html
* samples/2d/page-mapbox-planign-geoportail-bundle.html

versions du SDK (develop):

* "ol": "5.3.0",
* "ol-mapbox-style": "4.2.1",
* "itowns": "^2.27.0",
* "proj4": "2.6.2",
* "three": "^0.121.1",
* "three.meshline": "1.2.0",
* "geoportal-extensions-itowns": "2.3.0",
* "geoportal-extensions-openlayers": "3.0.13",

[x] **TODO :**
> creer l'exemple *samples/2d/page-mapbox-planign-bundle.html* sur la branche de la PR et develop... Et ne pas utiliser l'autoconf pour les tests de perf (merge avec develop pour recuperer la fonctionnalité) !

ol5 vs ol6 

* chargement de la page
![Capture-3-load](https://user-images.githubusercontent.com/10401006/107956223-24093b00-6f9f-11eb-99fb-efdfb365d162.png)

* zoom (x16)
![Capture-3-zoom](https://user-images.githubusercontent.com/10401006/107956311-4602bd80-6f9f-11eb-9b28-26b7aaea74dc.png)

* zoom avec la souris
![Capture-3-zoom-souris](https://user-images.githubusercontent.com/10401006/107956339-5155e900-6f9f-11eb-831f-57187e6d3c4c.png)

* déplacement sur la carte
![Capture-3-move](https://user-images.githubusercontent.com/10401006/107956361-5b77e780-6f9f-11eb-8f35-5d5c409c4392.png)


**Remarques :**

    Ce n'est pas ouf !?
    Difficile de voir une grosse difference dans la performance !?
    Il semble avoir une meilleur gestion 
    * du déplacement / zoom sur la carte
    * sur la mémoire (garbage collector)
    * sur le paint

**Conclusion :**

    Cette version n'apporte rien en terme de performance, mais cet upgrade nous permet d’espérer des améliorations futures...

## Test de rendu (PLAN.IGN)

* ol5 / olms 4.2.1

![Capture-2 0](https://user-images.githubusercontent.com/10401006/107956433-70ed1180-6f9f-11eb-8bed-489d845fc701.png)
![Capture-2 0 1](https://user-images.githubusercontent.com/10401006/107956438-73e80200-6f9f-11eb-8496-83d6fdbb2411.png)

* ol6 / olms 4.2.1

![Capture-2 1](https://user-images.githubusercontent.com/10401006/107956458-7c403d00-6f9f-11eb-9067-7d8bcb92291a.png)

* ol6 / olms 6.3.1

![Capture-2 2](https://user-images.githubusercontent.com/10401006/107956505-895d2c00-6f9f-11eb-971e-a790b842b842.png)
![Capture-2 2 1](https://user-images.githubusercontent.com/10401006/107956521-8cf0b300-6f9f-11eb-99a4-cef42f168e8d.png)

**Remarques :**

* Le zoom me semble plus fluide
* Le *repaint* est plus intelligent car tout n'est pas systematiquement redessiné lors d'un zoom ou deplacement...
* Les artifacts des tuiles ont disparu
* Certains rendus ne fonctionnent pas (ex. metro)
* Le rendu sur le deplacement de la carte est meilleur (pas d'affichage brusque de tuiles)

**Conclusion :**

    Le rendu de la couche PLAN.IGN doit être revalidé par les équipes qui l'ont conçu car il y'a des changements sur le rendu !

## Review impl. VectorTile

> contrôler l'impl de la classe *VectorTile*

2021-02-15 14:22 UTC, lowzonenose requested changes
:heavy_check_mark:  Rapport de Review 
:heavy_check_mark: Modifications (olms 6.3.1)
:heavy_check_mark: Merge (develop)

:boom: En attente des **releases** des extensions (ol6) pour valider la PR !

        "geoportal-extensions-itowns": "2.3.2",
        "geoportal-extensions-openlayers": "3.0.15",

2021-02-15 14:52 UTC, elias75015 commented
PR bloquée par le status à faire sur le rendu du vecteur tuilé avec OL6 / OLMS 6.3.1

Voir avec les concepteurs de la couche PLAN.IGN. Eventuellement mettre à disposition un démonstrateur PLAN.IGN avec OL6 vs OL5, pour repérer facilement les différences de rendu.

2021-05-05 11:08 UTC, elias75015 approved these changes
OK pour moi

2021-08-03 15:36 UTC, merged