Ajout des evolutions des extensions (feature-import-editable)
IGNF/geoportal-sdk pull request #83
Opened 2021-07-21 10:48 UTC by lowzonenose

Edition des vecteurs : GPX, KML et GeoJSON
cf. https://github.com/IGNF/geoportal-extensions/pull/307

2022-02-08 18:26 UTC, elias75015 commented
Test sur le portail de ce SDK sur la brache feature/import-editable :+1: 

- import d'un geojson
- modification du texte de feature : NOK

Dès qu'on bouge la souris, la popup dont on veut modifier le texte disparait

2022-02-08 18:34 UTC, elias75015 commented
Test sur le portail de ce SDK sur la brache feature/import-editable :

- import d'un geojson
- modification du texte de feature : NOK

Dès qu'on bouge la souris, la popup dont on veut modifier le texte disparait.

C'est le cas pour toutes les pop-up, même celles de l'outil de dessin, quand on veut ajouter une description !

2022-02-08 18:34 UTC, elias75015 requested changes
Problème avec les pop-up qui disparaissent dès le premier mouvement de souris

2022-02-09 07:44 UTC, lowzonenose commented
> Testé avec ce SDK, branches feature/import-editable de portail-visu et portail-front.

Bonne version _mergée_ avec **develop**, et poussée sur le dépôt.
Tu peux tester.

2022-02-09 13:58 UTC, elias75015 approved these changes

2022-02-09 14:40 UTC, merged